name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when you push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version to use (e.g., 20, 18, etc.)
          cache: 'npm' # Caches npm dependencies to speed up builds

      - name: Install dependencies
        run: npm install # Installs all packages listed in package.json

      - name: Build project
        run: npm run build # Runs the 'build' script defined in package.json (Vite build)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' # Only deploy if pushing to main branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub automatically provides this token
          publish_dir: ./dist # The directory containing your built files (Vite outputs to 'dist')
          # If you use a custom domain, you might need to specify cname: yourdomain.com
